# Generated by Django 3.0.4 on 2020-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmanager',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='telegram',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
